services:
  backend:
    build: .
    container_name: mumul-backend
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
